
[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = []

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xeaeaea"
yellow = "0xe6c547"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[debug]
log_level = "Warn"
persistent_logging = true
print_events = false
render_timer = false

[env]
TERM_PROGRAM = "Alacritty"

[font]
size = 17.0

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[mouse]
hide_when_typing = true

# [mouse.hints]
# launcher = "open"
# modifiers = "Command|Shift"

[scrolling]
history = 50000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 3
y = 3

[general]
working_directory = "None"

[terminal]
