[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
let g:asyncomplete_auto_popup = 1
let g:asyncomplete_auto_completeopt = 1
let g:asyncomplete_popup_delay = 200
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
depends = 'asyncomplete.vim'
hook_source = '''
  au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
      \ 'name': 'file',
      \ 'priority': 3,
      \ 'allowlist': ['*'],
      \ 'completor': function('asyncomplete#sources#file#completor'),
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'
depends = 'asyncomplete.vim'
hook_add = '''
  au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
      \ 'name': 'buffer',
      \ 'priority': 4,
      \ 'allowlist': ['*'],
      \ 'blocklist': ['go'],
      \ 'completor': function('asyncomplete#sources#buffer#completor'),
      \ 'config': {
      \    'max_buffer_size': 5000000,
      \  },
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-necosyntax.vim'
depends = ['neco-syntax']
hook_source = '''
  au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#necosyntax#get_source_options({
      \ 'name': 'necosyntax',
      \ 'priority': 7,
      \ 'allowlist': ['*'],
      \ 'completor': function('asyncomplete#sources#necosyntax#completor'),
      \ }))
'''

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'rhowardiv/nginx-vim-syntax'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'bfontaine/Brewfile.vim'

[[plugins]]
repo = 'vim-scripts/logstash.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'plytophogy/vim-virtualenv'

[[plugins]]
repo = 'PieterjanMontens/vim-pipenv'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'fuadsaud/vim-react-snippets'

[[plugins]]
repo = 'pgilad/vim-react-proptypes-snippets'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = 'kana/vim-textobj-user'

[[plugins]]
repo = 'PeterRincker/vim-argumentative'

[[plugins]]
repo = 'junegunn/vim-slash'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-fugitive'
augroup = 'fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
augroup SetColorScheme
    au!
    au VimEnter * nested colorscheme iceberg
augroup END
'''
