# Install command-line tools using Homebrew
# Credit: https://github.com/mathiasbynens/dotfiles
# Usage: `brew bundle Brewfile`

# fix any issues
doctor

tap --repair

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
install luajit
# Install GNU `sed`, overwriting the built-in `sed`
install gnu-sed --default-names
# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
install bash
install bash-completion

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --with-lua
install macvim --with-cscope --with-lua --custom-icons --with-luajit --override-system-vim
install homebrew/dupes/grep
install homebrew/php/php55 --with-gmp

# Install other useful binaries
install lua
install ack
install ag
install coreutils
install fasd
install findutils
install git
install hub
install git-extras
install htop-osx
install hub
install id3tool
install imagemagick --with-webp
install lesspipe
install lua
install macvim --with-cscope --with-lua --override-system-vim
install man2html
install maven
install mongo
install nmap
install node
install pv
install python
install rename
install ruby
install sl
install tmux
install tree
install webkit2png
install jmeter
install md5sha1sum
install redis

tap caskroom/cask
install brew-cask

linkapps

# Remove outdated versions from the cellar
cleanup
